const ZH = {
    lang: {
        title: '',
        placeholder: '请输入',
        authentication: {
            confirmName: '确认人姓名',
            confirmTel: '确认人电话',
            registCode: '资质注册号',
            IDPathImage: '认领人手持身份证照',
            catchIDImage: '认领人手持身份证照',
            facePhotoPath:'门脸照片',
            licensePath: '资质证照',
            copyPath: '专业资质证书',
            IDcode: '认领人身份证号码',
            othersPath: '其它证明材料',
            confirmPath: '认领确认书',
            confirmNamePlace: '请输入确认人的姓名',
            confirmTelPlace: '认领审核过程会致电该电话，请保持电话畅通',
            registCodePlace: '营业执照号码或组织机构代码',
            IDPathImagePlace: '请确保身份证原件信息清晰完整、人员面部清晰、上半身可见。',
            catchIDImagePlace: '请确保身份证原件信息清晰完整、人员面部清晰、上半身可见。',
            licensePathPlace: '营业执照或组织机构代码证',
            IDcodePlace: '请输入本人身份证号码',
            othersPathPlace: '（可以添加3张照片）',
            copyPathPlace: '行业资质、资格证书等复印件',
            confirmPathPlace: '请下载确认书模板、填写盖章后上传',
        },
        merchantDetail: {
            name: '服务商名称',
            type: '服务商类型',
            serviceType: '服务类型',
            portName: '服务港口',
            service: '提供的服务',
            address: '地址',
            linkman: '联系人',
            landLine: '座机号',
            mobileNumber: '手机号',
            email: '电子邮箱',
            thumb: '服务商家及产品的图片或文件',
            namePlace: '输入标注的企业或机构的名称',
            servicePlace: '请简短说明公司提供的服务内容，便于用户搜索发现',
            addressPlace: '公司的注册地址或经营地址，务必填写完整，确保在海图/地图模式下正确显示',
            linkmanPlace: '请输入联系人姓名',
            landLinePlace: '请输入公司/机构固定电话号码',
            mobileNumberPlace: '请输入联系人的手机号码',
            emailPlace: '请输入业务联系Email',

        }
    }
};
export default ZH;
